import {heightDevice, widthDevice} from 'assets/constans';
import {Platform, StyleSheet} from 'react-native';
import Colors from 'theme/Colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    // alignItems: 'center',
  },
  containerScreen: {flex: 1, backgroundColor: 'white'},
  wrapperScrollView: {flex: 1},
  modalCart: {
    position: 'absolute',
    width: widthDevice - 50,
    borderRadius: 40,
    left: 25,
    bottom: 10,
  },
  wrapperEmpty: {
    height: heightDevice * 0.4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textEmpty: {paddingVertical: 10, color: Colors.whiteColor},
  content: {
    flex: 1,
    backgroundColor: Colors.backgroundColor,
    alignItems: 'center',
  },
  wrapperIndicator: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 15,
    paddingHorizontal: 15,
    borderBottomColor: Colors.border,
    borderBottomWidth: 1,
    borderStyle: 'solid',
  },
  indicatorTitle: {
    position: 'absolute',
    left: widthDevice / 2 - 40,
    top: 0,
  },
  tabCategory: {
    paddingHorizontal: 10,
    justifyContent: 'center',
    flex: 1,
    backgroundColor: Colors.whiteColor,
    alignItems: 'center',
  },
  tabCategoryActive: {
    paddingHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: Colors.buttonTextColor,
    borderStyle: 'solid',
  },
  contents: {
    paddingHorizontal: 5,
    flex: 1,
    paddingBottom: 10,
  },
  styleContainerProduct: {
    width: (widthDevice - 36) / 2,
    minHeight: ((widthDevice - 36) / 2) * (151 / 171),
    marginBottom: 10,
    marginHorizontal: 6,
  },
  textCate: {
    textAlign: 'center',
    marginBottom: 19,
  },
  errorContainer: {
    // justifyContent: 'center',
    width: widthDevice,
    paddingTop: 50,
    // flex: 1,
    height: heightDevice,
    // backgroundColor: 'red',
    alignItems: 'center',
  },
  headerDelivery: {
    width: '49%',
    justifyContent: 'center',
    alignItems: 'center',
    height: '90%',
    borderRadius: 25,
  },
  styleImageProduct: {
    width: (widthDevice - 36) / 2,
    height: ((widthDevice - 36) / 2) * (151 / 171),
    // borderRadius: 10,
    // backgroundColor: 'red',
    alignSelf: 'center',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  styleModalCart: {
    position: 'absolute',
    bottom: 0,
    height: heightDevice * 0.09 + 10,
    alignItems: 'flex-start',
    width: widthDevice,
    paddingTop: 10,
    // left: -widthDevice / 2,
  },
  titleCategory: {
    color: '#170A08',
    paddingHorizontal: 10,
    // backgroundColor: 'red',
    textAlign: 'center',
    // alignSelf: 'center',
    paddingVertical: 25,
  },
  containerDropDownHeader: {
    flex: 1,
    backgroundColor: 'white',
    paddingHorizontal: 5,
    paddingBottom: 10,
  },
  wrapperIconDown: {
    // backgroundColor: 'red',
    paddingHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  wrapperItemDropdown: {
    flex: 1,
    // backgroundColor: 'yellow',
    paddingHorizontal: 5,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  activeItemDropdown: {
    fontSize: 13,
    fontFamily: 'SVN-Poppins-SemiBold',
    color: Colors.buttonTextColor,
  },
  wrapperIconDropDown: {
    // backgroundColor: 'red',
    paddingHorizontal: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  wrapperHeaderDelivery: {
    flexDirection: 'row',
    borderRadius: 25,
    alignSelf: 'center',
    marginVertical: 10,
    width: '50%',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 2,
    paddingVertical: 2,
    height: 32,
    backgroundColor: '#EFEFEF',
  },
  smallIcon: {width: 20, height: 20, borderRadius: 20},
  headerLineTitle: {
    flexDirection: 'row',
    paddingLeft: 16,
    alignItems: 'center',
  },
  wrapperTitleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    alignItems: 'center',
    borderStyle: 'solid',
    height: heightDevice * 0.07,
    borderBottomColor: '#E9E9E9',
    borderBottomWidth: 1,
    paddingLeft: 5,
    // backgroundColor: 'green',
  },
  newTabHeader: {
    width: widthDevice,
    height: Platform.OS === 'android' ? 90 : 90,
    backgroundColor: Colors.whiteColor,
    position: 'absolute',
    top: 0,
    elevation: 2,
    zIndex: 1000,
  },
  containerFlatlist: {
    zIndex: 1000,
    paddingTop: 16,
    paddingLeft: 6,
    backgroundColor: Colors.backgroundColor,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  pointSeparator: {
    backgroundColor: 'white',
  },
  separatorLine: {
    width: widthDevice - 20,
    paddingHorizontal: 5,
    backgroundColor: '#E9E9E9',
  },
  textLoading: {textAlign: 'center', color: Colors.buttonTextColor},
  wrapperLoading: {justifyContent: 'center', flex: 1},
  modalNoti: {
    width: widthDevice - 40,
    minHeight: '35%',
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    paddingVertical: 5,
  },
  containerModalCategory: {
    paddingTop: 20,
    backgroundColor: Colors.backgroundColor,
    width: widthDevice - 24,
    // height: heightDevice * 0.634,
    borderRadius: 17,
  },
  buttonConfirmNewOrder: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.buttonTextColor,
    marginTop: 30,
    height: 41,
    width: 133,
    borderRadius: 20,
  },
  imageStyle: {
    width: 120,
    height: 50,
  },
});

export default styles;
