import {StyleSheet} from 'react-native';
import {widthDevice, heightDevice} from 'assets/constans';
import Colors from 'theme/Colors';
const styles = StyleSheet.create({
  // ------------ NEW -----------------------
  descriptionText: {
    fontStyle: 'italic',
    paddingVertical: 3,
    // color: Colors.secondary,
  },
  paddingTop16: {
    paddingTop: 16,
  },
  toggledStyle: {
    borderBottomColor: Colors.border,
    borderBottomWidth: 1,
    borderStyle: 'dashed',
    paddingBottom: 15,
  },
  textAreaNote: {
    textAlign: 'right',
    paddingHorizontal: 10,
    color: '#636363',
  },
  paddingVertical10: {paddingVertical: 10},
  paddingHorizontal10: {paddingHorizontal: 10},
  logoTea: {height: 20, width: 20, borderRadius: 4, marginRight: 14},
  warningText: {color: Colors.warning, fontStyle: 'italic'},
  wrapperScrollView: {
    flex: 1,
    backgroundColor: Colors.backgroundColor,
    paddingTop: 10,
  },
  wrapperPrimaryLine: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  wrapperContent: {
    paddingHorizontal: 12,
    // backgroundColor: 'red',
    flex: 1,
  },
  wrapperComming: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: '#FFF5C4',
    borderRadius: 4,
  },
  wrapperLine: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 15,
  },
  wrapperCode: {
    paddingHorizontal: 15,
    paddingVertical: 2,
    borderRadius: 12,
    marginVertical: 6,
    backgroundColor: '#66BB6A',
    alignSelf: 'flex-start',
  },
  wrapperEmpty: {
    height: heightDevice * 0.4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textEmpty: {paddingVertical: 10, color: Colors.secondary},
  textInput: {
    position: 'absolute',
    width: '100%',
    // height: 100,
    top: 0,
    // backgroundColor: 'green',
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0,
    paddingVertical: 20,
    flex: 1,
  },
  removeAppliedBtn: {
    position: 'absolute',
    left: 10,
    top: -3,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  wrapperGatewayItem: {
    marginHorizontal: 10,
    marginVertical: 1,
    // backgroundColor: 'red',
    borderColor: Colors.border,
    borderBottomWidth: 0.7,
    borderStyle: 'solid',
    paddingHorizontal: 10,
    paddingVertical: 20,
  },
  header: {
    backgroundColor: Colors.whiteColor,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wrapperTitleModal: {
    paddingBottom: 8,
    // marginTop: 10,
    marginBottom: 5,
    // width: widthDevice,
    alignItems: 'center',
    // alignSelf: 'center',
    borderBottomColor: Colors.border,
    borderBottomWidth: 1,
    borderStyle: 'solid',
  },
  topUpBtn: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 4,
    backgroundColor: Colors.buttonTextColor,
    // alignSelf: 'center',
  },
  whiteText: {color: Colors.whiteColor},
  voucherWarningText: {
    paddingHorizontal: 5,
    // alignSelf: 'center',
    color: Colors.warning,
    // fontStyle: 'italic',
  },
  lineVoucherInfo: {
    paddingVertical: 2,
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: 'red',
  },
  codesLengthText: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 35,
    alignItems: 'center',
    paddingHorizontal: 5,
    paddingVertical: 5,
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 12,
    backgroundColor: '#F1DCB1',
  },
  topupSection: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  labelVoucher: {
    width: 20,
    height: 20,
    borderRadius: 16,
    marginBottom: 10,
    backgroundColor: '#EF0000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {position: 'absolute', top: 15, left: 16},
  storeSection: {
    paddingVertical: 5,
    backgroundColor: Colors.whiteColor,
    marginBottom: 10,
    paddingHorizontal: 15,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // backgroundColor: 'red',
    paddingVertical: 12,
    // paddingHorizontal: 10,
    borderBottomColor: '#E9E9E9',
    borderBottomWidth: 0.7,
    borderStyle: 'solid',
  },
  rowLineBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  locationBtn: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: '#F1DCB1',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  decorateLine: {
    height: 1,
    flex: 1,
    backgroundColor: Colors.border,
    // marginHor: 5,
  },
  inputArea: {
    marginLeft: 40,
    minHeight: 40,
    paddingRight: 10,
    color: Colors.secondary,
  },
  iconText: {position: 'absolute', top: 15, left: 15},
  discountText: {
    // color: '#EF0000',
    fontWeight: '600' || 'bold',
  },
  wrapperInputArea: {
    minHeight: 60,
    backgroundColor: Colors.backgroundColor,
    borderRadius: 8,
    marginTop: 10,
    marginHorizontal: 15,
    paddingVertical: 5,
  },
  textSecondary: {color: '#636363'},
  saveModalBtn: {
    backgroundColor: Colors.buttonTextColor,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    width: widthDevice / 1.5,
    // position: 'absolute',
    // bottom: 15,
    alignSelf: 'center',
    elevation: 10,
    zIndex: 100,
    marginBottom: 5,
    paddingVertical: 12,
  },
  wrapperVoucherItem: {
    padding: 10,
    marginHorizontal: 15,
    borderStyle: 'solid',
    borderWidth: 0.7,
    borderRadius: 12,
    borderColor: Colors.border,
  },
  wrapperVoucherInfo: {
    paddingVertical: 5,
    // borderBottomColor: 'lightgray',
    // borderBottomWidth: 1,
    // borderStyle: 'dashed',
  },
  applyVoucherBtn: {
    paddingVertical: 6,
    marginVertical: 5,
    paddingHorizontal: 12,
    backgroundColor: Colors.buttonTextColor,
    justifyContent: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
  },
  wrapperBottomSheet: {
    flex: 1,
    marginBottom: 50,
    // backgroundColor: 'red',
  },
  iconCloseModal: {
    position: 'absolute',
    top: -5,
    right: 15,
    padding: 5,
    zIndex: 200,
  },
  activeOption: {
    borderColor: Colors.secondary,
    // borderWidth: 1,
    backgroundColor: Colors.backgroundColor,
    // borderStyle: 'dashed',
    // paddingHorizontal: 10,
    flexDirection: 'row',
    padding: 10,
    marginHorizontal: 15,
    marginVertical: 12,
    alignItems: 'center',
    borderRadius: 16,
  },
  wrapperOption: {
    flexDirection: 'row',
    paddingBottom: 15,
    marginVertical: 10,
    paddingRight: 15,
    paddingLeft: 5,
    marginHorizontal: 16,
    // backgroundColor: 'red',
    paddingVertical: 5,
    // borderRadius: 16,
    borderBottomColor: '#E9E9E9',
    borderBottomWidth: 0.5,
    borderStyle: 'solid',
    alignItems: 'center',
  },
  bottomSheetBorder: {
    borderTopWidth: 2,
    borderTopColor: '#E9E9E9',
    borderStyle: 'solid',
  },
  imageStyle: {
    width: 34,
    marginRight: 12,
    height: 34,
    resizeMode: 'cover',
    borderRadius: 7,
  },
  wrapperStoreInfo: {
    flexDirection: 'row',
    paddingBottom: 6,
    paddingTop: 12,
    // paddingHorizontal: 10,
    alignItems: 'center',
  },
  wrapperPaymentName: {
    flexDirection: 'row',
    paddingVertical: 2,
    justifyContent: 'center',
    flex: 1,
    alignItems: 'center',
  },
  storeName: {fontSize: 13, color: Colors.buttonTextColor, paddingBottom: 2},
  storeAddress: {color: '#636363'},
  showMoreText: {color: Colors.secondary, marginRight: 3, marginBottom: 2},
  tabOption: {
    flex: 1,
    alignItems: 'center',
    // paddingTop: 5,
    justifyContent: 'center',
    paddingHorizontal: 5,
    flexDirection: 'row',
  },
  saveOrderBtn: {
    flex: 1,
    alignItems: 'center',
  },
  contentContainer: {
    backgroundColor: Colors.whiteColor,
    marginBottom: 10,
    paddingHorizontal: 15,
  },
  paymentGateway: {
    padding: 15,
    backgroundColor: Colors.whiteColor,
    marginBottom: 10,
  },
  containerModalPicker: {
    paddingBottom: 20,
    marginBottom: 20,
    flex: 1,
    alignSelf: 'center',
    width: widthDevice,
  },

  titleSectionPicker: {
    paddingBottom: 10,
    marginBottom: 5,
    alignItems: 'center',
    borderBottomColor: Colors.border,
    borderBottomWidth: 0.7,
    borderStyle: 'solid',
  },
  itemTimePicker: {
    borderBottomWidth: 0.5,
    marginHorizontal: 20,
    paddingVertical: 10,
    paddingTop: 15,
    borderBottomColor: Colors.border,
    // marginVertical: 5,
    // justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    borderStyle: 'solid',
  },
  selectedLabel: {
    position: 'absolute',
    top: 0,
    right: 0,
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 16,
    backgroundColor: Colors.buttonTextColor,
  },
  imageStyleIcon: {
    width: 20,
    marginRight: 7,
    height: 20,
    resizeMode: 'cover',
    marginTop: 1,
    borderRadius: 4,
  },
  wrapperAction: {
    position: 'absolute',
    bottom: 0,
    height: 100,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 2,
    width: widthDevice,
    backgroundColor: Colors.buttonTextColor,
  },
  wrapperTab: {
    height: 45,
    backgroundColor: '#FFFFFF',
    width: widthDevice,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  paymentSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 7,
    paddingHorizontal: 10,
  },
  verticalLine: {width: 1, height: 20, backgroundColor: 'lightgray'},
  textTitle: {
    // paddingHorizontal: 15,
    paddingBottom: 4,
    paddingTop: 16,
    fontSize: 16,
  },
  textShop: {
    marginStart: 35,
    fontSize: 14,
    marginTop: 4,
    fontWeight: '600',
    color: 'black',
  },
  textCreateOrder: {
    color: 'white',
  },
  container: {flex: 1, backgroundColor: 'white'},

  storeText: {
    marginStart: 10,
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
  },
  voucherSection: {
    paddingHorizontal: 15,
    marginTop: 5,
  },

  titleShipment: {
    paddingHorizontal: 10,
    paddingTop: 5,
    color: Colors.textGrayColor,
  },
  separatorLine: {
    width: widthDevice - 20,
    paddingHorizontal: 5,
    backgroundColor: '#E9E9E9',
  },
  buttonTextInput: {
    flexDirection: 'row',
    borderRadius: 10,
    borderColor: 'green',
    height: 40,
    width: widthDevice - 20,
    backgroundColor: Colors.whiteColor,
    justifyContent: 'space-between',
  },
  buttonTextInputError: {
    flexDirection: 'row',
    borderRadius: 10,
    height: 40,
    width: widthDevice - 20,
    backgroundColor: Colors.whiteColor,
    justifyContent: 'space-between',
  },

  styleWrapperTimePicker: {
    width: (widthDevice - 20) / 3 + 30,
    // fontStyle: 'italic',
    // color: 'red',
    fontSize: 13,
    fontFamily: 'SVN-Poppins-Medium',
    borderWidth: 2,
    borderColor: '#DFDFDF',
    justifyContent: 'center',
    borderRadius: 5,
    paddingHorizontal: 5,
  },

  styleTextInput: {
    width: (widthDevice - 20) / 3 + 30,
    fontSize: 13,
    fontFamily: 'SVN-Poppins-Medium',
    borderWidth: 1,
    borderColor: '#C2C2C2',
    borderRadius: 5,
    paddingHorizontal: 10,
  },
  styleTextInputNote: {
    width: ((widthDevice - 20) * 2) / 3 - 40,
    color: Colors.blackColor,
    fontSize: 14,
    fontFamily: 'SVN-Poppins-Medium',
    borderWidth: 1,
    borderColor: '#C2C2C2',
    borderRadius: 5,
    paddingHorizontal: 10,
  },
  pointSeparator: {
    backgroundColor: '#E9E9E9',
  },
  note: {
    fontStyle: 'italic',
    fontSize: 16,
    color: 'red',
    textAlign: 'center',
    padding: 10,
  },
  wrapperButtonWithAddress: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    paddingTop: 5,
    marginBottom: 5,
  },
  wrapperButton: {
    alignItems: 'center',
    paddingTop: 0,
    marginBottom: 15,
    marginTop: 35,
  },
  button: {
    width: 0.65 * widthDevice,
    height: 45,
    borderRadius: 40,
    backgroundColor: Colors.buttonTextColor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  productSection: {
    height: 300,
  },

  contentStore: {flex: 1},
  storeAddressText: {
    marginHorizontal: 10,
    fontSize: 14,
    fontStyle: 'italic',
  },
  changeAddressText: {
    color: '#00A2F3',
    fontSize: 12,
    alignSelf: 'flex-end',
    textDecorationLine: 'underline',
  },
  itemVoucher: {
    flexDirection: 'row',
    paddingStart: widthDevice / 2.8,
    marginTop: 2,
    marginBottom: 5,
  },
  contentTotalText: {
    color: Colors.blackColor,
  },
  contentTotal: {
    color: Colors.buttonTextColor,
  },
  paymentContainer: {
    justifyContent: 'space-between',
  },
  discount: {
    fontWeight: 'bold',
    fontSize: 14,
    color: Colors.buttonTextColor,
  },
  titleDiscount: {
    fontSize: 13,
  },
});

export default styles;
