import {heightDevice, widthDevice} from 'assets/constans';
import {StyleSheet} from 'react-native';
import Colors from 'theme/Colors';

const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: Colors.backgroundColor},
  contentWrapperItem: {
    flex: 1,
    // paddingLeft: 10,
    // backgroundColor: 'yellow',
    // width: widthDevice - 80,
  },
  productRestName: {
    fontSize: 14,
    color: Colors.buttonTextColor,
    paddingLeft: 5,
    // backgroundColor: 'red',
    marginVertical: 5,
  },
  contentExtra: {
    flex: 1,
  },
  contentPopup: {
    textAlign: 'center',
    color: 'black',
    paddingHorizontal: 10,
    paddingVertical: 20,
  },
  buttonConfirm: {
    backgroundColor: Colors.buttonTextColor,
    borderRadius: 20,
    width: 120,
    paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonConfirmBack: {
    borderRadius: 20,
    width: 120,
    paddingVertical: 6,
    justifyContent: 'center',
    borderWidth: 2,
    alignSelf: 'center',
    marginBottom: 10,
    borderColor: Colors.buttonTextColor,
    alignItems: 'center',
  },
  containerModalReorder: {
    paddingVertical: 10,
    backgroundColor: Colors.whiteColor,
    width: widthDevice - 24,
    paddingHorizontal: 10,
    borderRadius: 20,
  },
  button: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 20,
    width: 150,
    backgroundColor: Colors.buttonTextColor,
  },
  buttonCancel: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 150,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
    borderColor: Colors.redColor,
    borderWidth: 2,
  },
  textReview: {
    color: Colors.buttonTextColor,
    fontSize: 14,
  },
  buttonReview: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 150,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
    borderColor: Colors.buttonTextColor,
    borderWidth: 2,
  },
  textCancel: {
    fontSize: 14,
    color: Colors.redColor,
  },
  buttonRevert: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 150,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: Colors.buttonTextColor,
  },
  textRevert: {
    color: 'white',
    fontSize: 14,
  },
  note: {
    // fontStyle: 'italic',
    fontSize: 11,
    color: Colors.warning,
    textAlign: 'center',
    padding: 10,
    fontFamily: 'SVN-Poppins-Italic',
  },
  titleDiscount: {
    fontWeight: 'bold',
    fontSize: 13,
  },
  discount: {
    fontWeight: 'bold',
    color: Colors.buttonTextColor,
    fontSize: 14,
  },
  itemVoucher: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  voucherSection: {
    padding: 5,
  },
  contentTotal: {
    color: Colors.buttonTextColor,
  },
  totalTextService: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    borderBottomColor: 'black',
  },
  totalText: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 5,
    justifyContent: 'space-between',
    borderTopColor: '#E9E9E9',
    borderTopWidth: 1,
    borderStyle: 'solid',
    alignItems: 'center',
    marginHorizontal: 5,
  },
  textSvfee: {
    color: Colors.textGrayColor,
    fontSize: 14,
  },
  moneySvfee: {
    color: Colors.textGrayColor,
    fontSize: 14,
  },
  // paymentSection: {
  //   // height: 150,
  //   backgroundColor: 'blue',
  //   marginHorizontal: 10,
  //   paddingHorizontal: 5,
  //   paddingVertical: 10,
  //   borderBottomLeftRadius: 10,
  //   borderBottomRightRadius: 10,
  //   borderBottomColor: '#BDBDBD',
  //   borderBottomWidth: 1,
  //   borderStyle: 'dotted',
  // },
  imageStyle: {
    width: 45,
    height: 45,
    resizeMode: 'cover',
    alignSelf: 'center',
    marginRight: 10,
    borderRadius: 7,
  },
  imageStyleMessage: {
    width: 65,
    height: 60,
    marginBottom: 10,
    // backgroundColor: 'red',
    borderRadius: 15,
  },
  inforContent: {
    marginLeft: 5,
    fontSize: 12,
    color: Colors.secondary,
    marginBottom: 5,
  },
  textQuantity: {marginTop: 0, paddingRight: 2, color: Colors.secondary},
  textPrice: {color: Colors.buttonTextColor, alignSelf: 'center'},
  wrapperProductName: {
    flexDirection: 'row',
    flex: 1,
    // backgroundColor: 'black',
  },
  textRevertErrorTittle: {
    textAlign: 'center',
  },
  textCancelError: {
    fontSize: 15,
    color: Colors.redColor,
    paddingVertical: 0,
    marginTop: 15,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  textCancelSuccess: {
    fontSize: 15,
    color: Colors.buttonTextColor,
    paddingVertical: 10,
  },
  wrapperButtonSectionConfirm: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingBottom: 20,
  },
  wrapperProductLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // backgroundColor: 'blue',
    alignItems: 'center',
  },
  itemWrapper: {
    flexDirection: 'row',
    backgroundColor: 'white',
    borderBottomWidth: 0.7,
    // paddingHorizontal: 10,
    // borderBottomColor: 'lightgrey',
    borderStyle: 'solid',
    borderBottomColor: Colors.border,
    // backgroundColor: 'green',
    alignSelf: 'center',
    paddingHorizontal: 5,
    paddingVertical: 10,
    marginHorizontal: 5,
  },
  separatorLine: {
    width: widthDevice - 40,
    paddingHorizontal: 5,
    backgroundColor: '#E9E9E9',
  },
  pointSeparator: {
    backgroundColor: '#E9E9E9',
  },
  shopWrapper: {
    // height: 100,
    // marginTop: 5,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 5,
    backgroundColor: 'red',
    // padding: 5,
  },
  inforSection: {
    // alignContent: 'center',
    backgroundColor: Colors.whiteColor,
    // paddingHorizontal: 10,
    borderRadius: 10,
    marginHorizontal: 10,
    paddingVertical: 5,
    marginTop: 5,
    // paddingVertical: 5,
    // height: heightDevice / 2,
    flex: 1,
  },
  // flatlist: {
  //   // marginTop: 5,
  //   // height: '100%',
  //   // marginHorizontal: 5,
  //   // backgroundColor: 'green',

  // },
  productName: {
    fontSize: 13,
    // flex: 1,
    // paddingHorizontal: 3,
    // backgroundColor: 'blue',
    // alignSelf: 'flex-start',
    // flexWrap: 'wrap',
  },
  contentPrice: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  contentWrapper: {
    // flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: Colors.whiteColor,
    borderRadius: 10,
    marginHorizontal: 10,
    marginTop: 10,
    marginBottom: 5,
    // width: widthDevice,
  },
  wrapperConfirm: {
    marginHorizontal: 10,
    paddingVertical: 10,
  },
  containerCancelModal: {
    width: widthDevice - 20,
    paddingVertical: 10,
    backgroundColor: 'white',
    borderRadius: 20,
  },
  headerCancelModal: {
    borderRadius: 20,
    paddingTop: 5,
    paddingBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contentCancel: {
    // paddingBottom: 10,
    // width: '100%',
    paddingHorizontal: 10,
    paddingVertical: 15,
    // backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionCancel: {
    paddingVertical: 10,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  buttonCancelModal: {
    width: 120,
    borderColor: Colors.buttonTextColor,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    paddingVertical: 6,
    borderWidth: 2,
  },
  buttonConfirmCancelModal: {
    width: 120,
    paddingVertical: 6,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: Colors.buttonTextColor,
  },
  orderInforLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 5,
  },
  buttonSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    // backgroundColor: 'green',
  },
  titleText: {
    color: Colors.textGrayColor,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
});

export default styles;
