import {heightDevice, widthDevice} from 'assets/constans';
import {Platform, StyleSheet} from 'react-native';
import Colors from 'theme/Colors';

const styles = StyleSheet.create({
  wrapperBellBtn: {
    flexDirection: 'row',
    width: 43,
    height: 43,
    borderRadius: 43,
    backgroundColor: 'white',
    opacity: 0.9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconSection: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    width: '50%',
    height: '100%',
    // backgroundColor: 'red',
    alignItems: 'center',
  },
  contentInfo: {
    backgroundColor: 'white',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    opacity: 0.8,
    flexDirection: 'row',
  },
  wrapperEmpty: {
    // height: heightDevice * 0.4,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  messageSection: {
    // flexDirection: 'row',
    // paddingHorizontal: 10,
    // width: 80,
    // alignSelf: 'flex-end',
    // marginRight: 20,
    // backgroundColor: 'red',
  },
  container: {
    width: widthDevice,
    height:
      Platform.OS === 'android' ? heightDevice * 0.09 : heightDevice * 0.07,
    backgroundColor: 'white',
    justifyContent: Platform.OS === 'android' ? 'flex-end' : 'center',
    // paddingHorizontal: 5,
    paddingBottom: 5,
  },
  containerHome: {
    width: widthDevice,
    height:
      Platform.OS === 'android' ? heightDevice * 0.08 : heightDevice * 0.07,
    backgroundColor: 'white',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 5,
    paddingBottom: 10,
  },
  containerHomeMain: {
    width: widthDevice,
    height: heightDevice * 0.08,
    // backgroundColor: 'red',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 5,
    paddingBottom: 10,
    zIndex: 2,
    opacity: 0.8,
  },
  content: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: widthDevice - 30,
    alignSelf: 'center',
    // backgroundColor: 'green',
    paddingHorizontal: 5,
    marginTop: 15,
  },
  containerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  imageAccount: {
    height: 25,
    width: 25,
    // marginRight: 10,
    // marginLeft: 10,
  },
  imageLocation: {
    height: 25,
    width: 25,
    marginRight: 1,
    // backgroundColor: 'green',
    alignSelf: 'center',
  },
  textHello: {
    color: Colors.textGrayColor,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  textName: {
    color: Colors.buttonTextColor,
    // lineHeight: 17,
    paddingHorizontal: 8,
    paddingVertical: 4,
    // backgroundColor: 'red',
  },
  cartSection: {
    position: 'absolute',
    top: -8,
    right: 8,
    width: 20,
    justifyContent: 'center',
    alignItems: 'center',
    height: 20,
    borderRadius: 20,
    backgroundColor: Colors.button2Color,
  },
  imageBell: {
    width: 19,
    height: 23,
    marginTop: 5,
  },
  containerModalNotify: {
    // paddingTop: 20,
    backgroundColor: Colors.backgroundColor,
    width: widthDevice - 24,
    borderRadius: 10,
    height: heightDevice * 0.69,
    paddingBottom: 20,
  },
  textModal: {
    textAlign: 'center',
    marginBottom: 10,
    marginTop: 12,
    color: 'white',
  },
  headerModal: {
    paddingVertical: 15,
    backgroundColor: Colors.primary,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantity: {
    backgroundColor: Colors.redColor,
    height: 10,
    width: 10,
    borderRadius: 18,
    marginLeft: -8,
    marginTop: -12,
  },
  textQuantity: {
    color: Colors.whiteColor,
    fontSize: 9,
    // marginRight: 1,
    marginBottom: 1,
  },
  buttonClose: {
    position: 'absolute',
    top: 10,
    right: 10,
    padding: 5,
  },
  errorContainer: {justifyContent: 'center', width: '100%', height: '100%'},
});

export default styles;
