import { heightDevice, widthDevice } from 'assets/constans';
import { StyleSheet } from 'react-native';
import Colors from 'theme/Colors';

const styles = StyleSheet.create({
  wrapperGetway: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
    paddingTop: 15,
    paddingBottom: 15,
    backgroundColor: 'lightpink',
    borderRadius: 10,
    paddingHorizontal: 10,
  },
  modalView: {
    backgroundColor: 'white',
    position: 'absolute',
    bottom: -heightDevice / 2,
    left: -widthDevice / 2,
    padding: 20,
    paddingHorizontal: 10,
    width: widthDevice,
    shadowColor: '#000',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  orderButton: {
    paddingVertical: 13,
    width: '80%',
    alignSelf: 'center',
    marginBottom: 30,
    marginTop: 12,
    backgroundColor: Colors.buttonTextColor,
    alignItems: 'center',
    borderRadius: 30,
  },
  warningMessage: { color: 'orange', padding: 5, fontSize: 12 },
  addressText: { color: Colors.textGrayColor, fontSize: 12, marginLeft: 10 },
  wrapperIconPayment: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: -50,
  },
  wrapperPayment: {
    flexDirection: 'row',
    padding: 10,
    justifyContent: 'space-between',
    backgroundColor: Colors.whiteColor,
    borderRadius: 10,
    alignItems: 'center',
    marginVertical: 5,
  },
  wrapperItemDropdown: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginVertical: 2,
    // backgroundColor: 'red',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomColor: 'lightgray',
  },
  containerDropDownHeader: {
    flex: 1,
    backgroundColor: 'white',
    paddingHorizontal: 5,
    paddingBottom: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    // elevation: 10,
    zIndex: 100,
  },
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  imageLogo: {
    height: 50,
    width: 50,
  },
  containerContent: {
    flex: 1,
    backgroundColor: Colors.backgroundColor,
    paddingHorizontal: 10,
  },
  wrapperStore: {
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    backgroundColor: Colors.whiteColor,
    paddingTop: 10,
    paddingHorizontal: 10,
    marginTop: 5,
  },
  wrapperTitleStore: {
    paddingVertical: 2,
    // flexDirection: 'row',
    // justifyContent: 'space-between',
  },
  wrapperStoreInfo: {
    flexDirection: 'row',
    paddingTop: 5,
    paddingBottom: 10,
    // borderBottomWidth: 1,
    borderBottomColor: 'lightgray',
    // borderStyle: 'dashed',
  },
  wrapperInputMoney: {
    paddingTop: 10,
    paddingBottom: 10,
    // borderBottomWidth: 2,
    borderBottomColor: 'lightgray',
    // borderStyle: 'dashed',
  },
  wrapeprNameStore: { flex: 1, paddingHorizontal: 5 },
  nameStore: { fontSize: 13, marginLeft: 5 },
  wrapperAddress: { paddingVertical: 5, marginRight: 15 },
  styleTextInput: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 12,
    color: Colors.buttonTextColor,
    fontWeight: 'bold',
    fontSize: 16,
    borderStyle: 'solid',
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 2,
    borderColor: Colors.buttonTextColor,
  },
  wrapperTotalMoney: {
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    backgroundColor: Colors.whiteColor,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  contentInfo: { flexDirection: 'row', justifyContent: 'space-between' },
  viewDot: {
    height: 12,
    width: 12,
    borderRadius: 12,
    backgroundColor: '#F6F6F6',
    marginTop: 6,
    marginLeft: -16,
  },
  viewDotR: {
    height: 12,
    width: 12,
    borderRadius: 12,
    backgroundColor: '#F6F6F6',
    marginTop: 6,
    marginRight: -16,
  },
  dottedLineContainer: {
    overflow: 'hidden',
    width: widthDevice - 32,
    position: 'absolute',
    bottom: 5,
    marginLeft: 6,
  },
  dottedLineDot: {
    borderStyle: 'dashed',
    borderWidth: 2,
    borderColor: '#BDBDBD',
    margin: -2,
    marginTop: 0,
  },
});
export default styles;
